#!/bin/sh
if [ -z $(pidof init|grep $(cat /tmp/var/run/jail.pid)) ]
then
  /usr/bin/jchroot -p /tmp/var/run/jail.pid  -n jail -f /etc/fstab  / /sbin/init &
sleep 5
fi
nsenter -t $(cat /tmp/var/run/jail.pid) -u -m -p -r /bin/sh
