#!/bin/sh

pid=$(pgrep -n init)

if [ $pid != 1 ]
then
  /bin/kill $pid
  while kill -0 $pid 2&>/dev/null; do 
      sleep 1
  done

  rm -rf /tmp/var/run/jail.pid
  rmmod virtual_fb
fi

echo "out of jail"
